services:
  db:
    container_name: sound-api-db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sdokUSMo9SP197SUAJL795kai
      POSTGRES_DB: sound_dna
    ports:
      - "5432:5432"
    volumes:
      - sound-api-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sound_dna"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    container_name: sound-api-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:sdokUSMo9SP197SUAJL795kai@db:5432/sound_dna?schema=public
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sound-api-db-data:
